### ISSUE TITLE
Update ungit to 1.5.0

### ISSUE THREAD

**Issue by bakkerthehacker** [jung-kim/atom-ungit#57]
The upstream ungit has been updated to 1.5.0 and atom ungit is still on 1.4.x

https://github.com/jung-kim/atom-ungit/blob/0bd9b86eb23813953aa039f0c048bd3d2d77840c/package.json#L18

**Comment by jung-kim** [comment]
Oh shoot, I don't use this fork at all.  haha I forgot I had this. 

I myself, and would recommend, using [FredrikNoren/ungit](https://github.com/FredrikNoren/ungit)

**Comment by bakkerthehacker** [comment]
I am confused what you mean by fork.  This is the atom bindings to enable ungit to run in atom, not the ungit repo itself.

**Comment by jung-kim** [comment]
Oh shoot! sorry you are absolutely right.  I've goofed.

Will bump the version soon

**Comment by jung-kim** [comment]
#58 merged
